version: '3.8'

services:
    db:
        image: postgres:latest
        container_name: postgres
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: on-money
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
